export const dataCards = [
  {
    title: 'Customer Care',
    description: 'Listening, Clarifying and Responding effectively',
    icon: 'heart',
    grade: 90,
    code: 'care',
    color: 'red',
  },
  {
    title: 'Contact Handling',
    description: 'Contact investigating and solving',
    icon: 'sign language',
    grade: 89,
    code: 'handling',
    color: 'brown',
  },
  {
    title: 'Product Knowledge',
    description: 'Products and processes mastering',
    icon: 'graduation',
    grade: 89,
    code: 'knowledge',
    color: 'green',
  },
  {
    title: 'Effective Response',
    description: 'Quick and quality contact resolution',
    icon: 'reply all',
    grade: 89,
    code: 'response',
    color: 'blue',
  },
  {
    title: 'Greetings',
    description: 'Proper call opening and closing',
    icon: 'handshake',
    grade: 89,
    code: 'greeting',
    color: 'orange',
  },
  {
    title: 'Contact Etiquette',
    description: 'Politness and proper handling',
    icon: 'balance scale',
    grade: 89,
    code: 'etiquette',
    color: 'grey',
  },
  {
    title: 'System Familiarities',
    description: 'System usage, follow up and registry',
    icon: 'cogs',
    grade: 89,
    code: 'system',
    color: 'olive',
  },
  {
    title: 'Sales Skills',
    description: 'Selling skills',
    icon: 'dollar',
    grade: 89,
    code: 'sales',
    color: 'teal',
  },
];
